export const REVIEWS_LOADED = 'REVIEWS_LOADED';

export const LOAD_REVIEW = 'LOAD_REVIEW';
export const REVIEW_LOADED = 'REVIEW_LOADED';

export const SAVE_REVIEW = 'SAVE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
