export const LOAD_USERS = 'LOAD_USERS';
export const USERS_LOADED = 'USERS_LOADED';
export const BLOCK_USER = 'BLOCK_USER';
export const DELETE_USER = 'DELETE_USER';

export const CREATE_USER = 'CREATE_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const UPDATE_USER = 'UPDATE_USER';

export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const USER_DATA_LOADED = 'USER_DATA_LOADED';

export const USERS_LOAD_ROLES = 'USERS_LOAD_ROLES';
export const USERS_ROLES_LOADED = 'USERS_ROLES_LOADED';

export const CURRENT_USER_INFO_LOADED = 'CURRENT_USER_INFO_LOADED';

export const START_LISTEN_USERS = 'START_LISTEN_USERS';
export const STOP_LISTEN_USERS = 'STOP_LISTEN_USERS';
